#!/usr/bin/env python3
"""Remove placeholder company baselines generated by the bad automatic batch."""

import json
import os
import re
from pathlib import Path


VAULT = Path(os.path.expanduser(os.environ.get("ENTITY_VAULT", os.environ.get("CONCEPT_VAULT", "~/Desktop/c c/知识库/wiki"))))
ENTITIES_DIR = VAULT / "entities"
RELATIONS_DIR = VAULT / "relations"
BAD_RAW_SOURCE = "iFinD baseline 2026-05-26 automatic batch"
BAD_EVIDENCE_RE = re.compile(r"公司是行业主流的.+核心实体")
BAD_BATCH_RE = re.compile(r"\[\[iFinD baseline 2026-05-26 batch\d+\]\]")
STATIC_SECTIONS = ["基础画像", "产业链暴露", "关键数据", "风险与反证", "待核实问题", "iFinD 证据"]


def split_frontmatter(text):
    if not text.startswith("---\n"):
        return [], text
    lines = text.splitlines()
    for i in range(1, min(len(lines), 200)):
        if lines[i].strip() == "---":
            body = "\n".join(lines[i + 1 :])
            if text.endswith("\n"):
                body += "\n"
            return lines[1:i], body
    return [], text


def parse_json_list(value):
    try:
        parsed = json.loads(value)
        return parsed if isinstance(parsed, list) else []
    except Exception:
        return re.findall(r'"([^"]+)"', value)


def render_json_list(values):
    return "[" + ", ".join(json.dumps(v, ensure_ascii=False) for v in values) + "]"


def remove_from_frontmatter(fm_lines, key, bad_value):
    prefix = f"{key}:"
    changed = False
    for i, line in enumerate(fm_lines):
        if not line.startswith(prefix):
            continue
        values = parse_json_list(line.split(":", 1)[1].strip())
        new_values = [v for v in values if v != bad_value]
        if new_values != values:
            fm_lines[i] = f"{key}: {render_json_list(new_values)}"
            changed = True
    return changed


def remove_section(body, title):
    pattern = rf"\n?## {re.escape(title)}\s*\n+.*?(?=\n## |\Z)"
    return re.sub(pattern, "\n", body, flags=re.S)


def clean_entities():
    changed_files = []
    for path in ENTITIES_DIR.glob("*.md"):
        text = path.read_text(encoding="utf-8", errors="ignore")
        if BAD_RAW_SOURCE not in text:
            continue
        fm, body = split_frontmatter(text)
        changed = remove_from_frontmatter(fm, "raw_sources", BAD_RAW_SOURCE)
        evidence_match = re.search(r"## iFinD 证据\s*\n+.*?" + re.escape(BAD_RAW_SOURCE), body, flags=re.S)
        if evidence_match:
            for section in STATIC_SECTIONS:
                body = remove_section(body, section)
            changed = True
        if changed:
            new_text = "---\n" + "\n".join(fm) + "\n---\n" + body.strip() + "\n"
            path.write_text(new_text, encoding="utf-8")
            changed_files.append(path.name)
    return changed_files


def load_json(path, default):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path, data):
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def clean_entity_exposures():
    path = RELATIONS_DIR / "entity_exposures.json"
    data = load_json(path, {"entities": {}})
    removed = 0
    touched = 0
    for entity in list(data.get("entities", {})):
        concepts = data["entities"][entity].get("concepts", {})
        for concept in list(concepts):
            exp = concepts[concept]
            evidence = str(exp.get("evidence", ""))
            sources = [s for s in exp.get("sources", []) if not BAD_BATCH_RE.fullmatch(str(s))]
            if BAD_EVIDENCE_RE.search(evidence):
                del concepts[concept]
                removed += 1
                touched += 1
                continue
            if sources != exp.get("sources", []):
                exp["sources"] = sources
                touched += 1
        if not concepts and not data["entities"][entity].get("codes"):
            del data["entities"][entity]
    if touched:
        write_json(path, data)
    return removed, touched


def clean_evidence_index():
    path = RELATIONS_DIR / "evidence_index.json"
    data = load_json(path, {"items": []})
    old = data.get("items", [])
    new = []
    for item in old:
        source = str(item.get("source", ""))
        evidence = str(item.get("evidence", ""))
        if BAD_BATCH_RE.fullmatch(source) or BAD_EVIDENCE_RE.search(evidence):
            continue
        new.append(item)
    if len(new) != len(old):
        data["items"] = new
        write_json(path, data)
    return len(old) - len(new)


def main():
    files = clean_entities()
    removed_exposures, touched_exposures = clean_entity_exposures()
    removed_evidence = clean_evidence_index()
    print(json.dumps({
        "entities_cleaned": len(files),
        "sample_entities": files[:20],
        "entity_exposures_removed": removed_exposures,
        "entity_exposures_touched": touched_exposures,
        "evidence_index_removed": removed_evidence,
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
