#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || { printf '\n'; warn "输入流已关闭（EOF），向导中止。"; exit 1; }
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || { printf '\n'; warn "输入流已关闭（EOF），向导中止。"; exit 1; }
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE="${HOME}/.local/share/finance-workbench/alpha.env"
USER_MAP="${HOME}/.local/share/finance-workbench/beta-users.json"
mkdir -p "$(dirname "$ENV_FILE")"

banner "Hosted Alpha · Cloudflare Access 人工步骤"

say "本向导只配边缘认证和邀请名单，不改 8792 启动器、不 kickstart。"
say "配完的环境变量写到 ${ENV_FILE}；接到 start-finance-workbench 需你确认。"
note "现有隧道 a77-exec 已服务 *.industry7view.com；默认建议加 beta 主机名，而不是再开一条隧道。"
pause "准备好打开 Cloudflare 控制台了吗？"

# ── Stage 1: hostname ────────────────────────────────────────────────────
stage "确认公网主机名"
say "公网入口会变成这个主机名。Cloudflare Access 和 DNS 都绑它。"
note "建议：beta.industry7view.com（已有同域隧道）。不要用正在跑的 archlume / exec-a77 / api-a77。"
ask ALPHA_HOSTNAME "公网主机名（例如 beta.industry7view.com）:"
if [[ -z "$ALPHA_HOSTNAME" ]]; then
  warn "主机名为空，向导中止。"
  exit 1
fi
write_env ALPHA_HOSTNAME "$ALPHA_HOSTNAME"

# ── Stage 2: tunnel ingress ──────────────────────────────────────────────
stage "给现有隧道加一条 ingress"
say "本机 cloudflared 已在跑（a77-exec）。要让公网打到 8792，在 ~/.cloudflared/config.yml 的 ingress 列表最前面加："
note "  - hostname: ${ALPHA_HOSTNAME}"
note "    service: http://127.0.0.1:8792"
step "先备份：cp ~/.cloudflared/config.yml ~/.cloudflared/config.yml.bak.\$(date +%Y%m%d%H%M%S)"
step "用编辑器把上面两行插到 ingress: 下面、现有 hostname 规则之前。"
step "DNS：cloudflared tunnel route dns a77-exec ${ALPHA_HOSTNAME}"
step "改完后重启隧道：sudo launchctl kickstart -k system/com.cloudflare.cloudflared  （若这条服务名不对，用 launchctl list | grep cloudflare 核对）"
warn "不要新建第二条 tunnel：一台 Mac 上两条 cloudflared 抢同一份 cert 会互相踩。"
pause "ingress + DNS 配好、隧道已重启后按 Enter"

# ── Stage 3: Access application ──────────────────────────────────────────
stage "Cloudflare Access 应用"
say "Access 在边缘做邮箱 OTP。后端再验一次 JWT，不信任明文邮箱头。"
open_url "https://one.dash.cloudflare.com/"
step "Zero Trust → Access → Applications → Add an application → Self-hosted。"
step "Application name 填 finance-workbench-alpha。"
step "Public hostname 填刚才的 ${ALPHA_HOSTNAME}（路径留空或 /）。"
step "Policy：Action = Allow；Include = Emails。先填你自己的邮箱，以后再加朋友。"
step "登录方式保持 One-time PIN（邮箱验证码），不必接 Google/GitHub IdP。"
pause "应用建好后按 Enter，下一屏要复制两个值"

# ── Stage 4: team domain + AUD ───────────────────────────────────────────
stage "粘贴 Team Domain 与 AUD"
step "还在这个 Access 应用页：找到 Application Audience (AUD) tag，整段复制。"
ask WORKBENCH_CF_ACCESS_AUD "粘贴 AUD tag:"
step "Team domain：Zero Trust → Settings → Custom Pages 附近，形如 <team>.cloudflareaccess.com。"
note "只要主机名，不要 https://。"
ask WORKBENCH_CF_ACCESS_TEAM_DOMAIN "Team domain（例如 xxx.cloudflareaccess.com）:"
if [[ -z "$WORKBENCH_CF_ACCESS_AUD" || -z "$WORKBENCH_CF_ACCESS_TEAM_DOMAIN" ]]; then
  warn "AUD 或 Team domain 为空，向导中止。重新跑即可，已写的值会保留。"
  exit 1
fi
write_env WORKBENCH_CF_ACCESS_AUD "$WORKBENCH_CF_ACCESS_AUD"
write_env WORKBENCH_CF_ACCESS_TEAM_DOMAIN "$WORKBENCH_CF_ACCESS_TEAM_DOMAIN"

# ── Stage 5: invite map ──────────────────────────────────────────────────
stage "邀请名单（邮箱 → user_id）"
say "后端用这份 JSON 把 Access 邮箱映射成仓内 user_id。文件不进 git。"
note "user_id 规则：字母/数字开头，只含 A-Za-z0-9._-，长度 ≤ 64。"
if [[ -f "$USER_MAP" ]]; then
  note "已有名单：${USER_MAP}"
  say "当前内容："
  sed 's/^/    /' "$USER_MAP" || true
fi
ask OWNER_EMAIL "你的登录邮箱:"
ask OWNER_USER "对应 user_id（建议 linxiaoqi5111）:"
OWNER_USER="${OWNER_USER:-linxiaoqi5111}"
INVITE_JSON=$(printf '{\n  "%s": "%s"\n}\n' "$OWNER_EMAIL" "$OWNER_USER")
if [[ -f "$USER_MAP" ]] && ! confirm "覆盖已有 ${USER_MAP}？选 N 则跳过写名单"; then
  note "保留原名单。"
else
  printf '%s' "$INVITE_JSON" > "$USER_MAP"
  chmod 600 "$USER_MAP"
  say "已写入 ${USER_MAP}："
  sed 's/^/    /' "$USER_MAP"
fi
write_env WORKBENCH_AUTH_USER_MAP "$USER_MAP"
write_env WORKBENCH_FULL_ACCESS_USERS "$OWNER_USER"
write_env WORKBENCH_QUOTA_EXEMPT_USERS "$OWNER_USER"
write_env WORKBENCH_DAILY_RUN_QUOTA "20"
write_env WORKBENCH_AUTH_MODE "cf_access"
note "再加朋友：编辑 ${USER_MAP} 加一行邮箱，并在 Access Policy 里也加同一个邮箱（双层白名单）。mtime 变化会热重载，不用重启。"

# ── Stage 6: how to enable — do NOT kickstart ────────────────────────────
stage "怎么接到 8792（本步只展示，不执行）"
say "alpha.env 已经写好。生产启动器现在没有 WORKBENCH_AUTH_MODE，8792 仍是本机自用。"
say "要上线时，把下面这段加进 ~/.local/bin/start-finance-workbench（GLM/中转段之后），然后："
note "  launchctl kickstart -k gui/\$(id -u)/com.a77.finance-workbench"
say ""
say "建议粘贴："
note "  # Hosted Alpha（由 scripts/hosted-alpha-wizard.sh 生成）"
note "  if [[ -f \"\$HOME/.local/share/finance-workbench/alpha.env\" ]]; then"
note "    set -a"
note "    source \"\$HOME/.local/share/finance-workbench/alpha.env\""
note "    set +a"
note "  fi"
warn "现在不要 kickstart。缺 AUD/名单时 cf_access 会让进程启动即抛，本机自用会挂。"
say "回滚：删掉这段 source，或把 alpha.env 里 WORKBENCH_AUTH_MODE 改成 off，再 kickstart。"
pause "看完接入方式后按 Enter"

finish
say "下一步（你确认后再做）：改启动器 → kickstart → 按 docs/workbench/hosted-alpha-gate.md §3 验收。"
note "本机探活应仍通：curl -s http://127.0.0.1:8792/api/health"
note "直打 /api/conversations 在 auth 打开后应返 401。"
